//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanLordlAPIs.Models.db_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthenticationToken
    {
        public System.Guid TokenId { get; set; }
        public System.Guid MemberId { get; set; }
        public bool IsActivated { get; set; }
        public Nullable<System.DateTime> DateGenerated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<System.Guid> FriendRequestId { get; set; }
        public Nullable<System.DateTime> VerifiedOn { get; set; }
    }
}
