//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanLordlAPIs.Models.db_Model
{
    using System;
    
    public partial class GetTenantsInGivenPropertyId_Result2
    {
        public System.Guid TenantId { get; set; }
        public System.Guid MemberId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<bool> IsVerifiedPhone { get; set; }
        public Nullable<bool> IsVerifiedWithSynapse { get; set; }
        public string Photo { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> LastPaymentDate { get; set; }
        public Nullable<bool> IsPaymentDueForThisMonth { get; set; }
        public System.Guid UnitId { get; set; }
        public string UnitRent { get; set; }
        public string UnitNumber { get; set; }
        public string TenantEmail { get; set; }
    }
}
