//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanLordlAPIs.Models.db_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MembersIPAddress
    {
        public int Id { get; set; }
        public Nullable<System.Guid> MemberId { get; set; }
        public string Ip { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
