//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanLordlAPIs.Models.db_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.MemberNotifications = new HashSet<MemberNotification>();
            this.MemberPrivacySettings = new HashSet<MemberPrivacySetting>();
        }
    
        public System.Guid MemberId { get; set; }
        public string Nooch_ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UDID1 { get; set; }
        public string UserName { get; set; }
        public string SecondaryEmail { get; set; }
        public string RecoveryEmail { get; set; }
        public string TertiaryEmail { get; set; }
        public string PinNumber { get; set; }
        public string Password { get; set; }
        public string ContactNumber { get; set; }
        public string Status { get; set; }
        public Nullable<bool> RememberMeEnabled { get; set; }
        public Nullable<System.Guid> NoochAccountId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> InvalidLoginTime { get; set; }
        public Nullable<int> InvalidLoginAttemptCount { get; set; }
        public Nullable<int> InvalidPinAttemptCount { get; set; }
        public Nullable<System.DateTime> InvalidPinAttemptTime { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string FacebookAccountLogin { get; set; }
        public Nullable<bool> AllowPushNotifications { get; set; }
        public string Photo { get; set; }
        public string FacebookPhoto { get; set; }
        public Nullable<bool> UseFacebookPicture { get; set; }
        public Nullable<bool> ClearTransactionHistory { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zipcode { get; set; }
        public string Country { get; set; }
        public Nullable<int> NoOfTransfersByPackage { get; set; }
        public Nullable<int> FreeTransfers { get; set; }
        public Nullable<bool> ShowInSearch { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Deposit { get; set; }
        public Nullable<System.DateTime> InviteReminderDate { get; set; }
        public string UserNameLowerCase { get; set; }
        public string TimeZoneKey { get; set; }
        public string Address2 { get; set; }
        public Nullable<int> TotalNoochTransfersCount { get; set; }
        public Nullable<int> TotalACHTransfersCount { get; set; }
        public Nullable<System.DateTime> ValidatedDate { get; set; }
        public Nullable<int> ValidationFailedCount { get; set; }
        public Nullable<System.Guid> InviteCodeId { get; set; }
        public Nullable<System.Guid> InviteCodeIdUsed { get; set; }
        public string Type { get; set; }
        public string SSN { get; set; }
        public Nullable<System.DateTime> UpgradeDate { get; set; }
        public Nullable<bool> IsVerifiedPhone { get; set; }
        public Nullable<decimal> LastLocationLat { get; set; }
        public Nullable<decimal> LastLocationLng { get; set; }
        public string AccessToken { get; set; }
        public Nullable<bool> IsFrequencyOn { get; set; }
        public Nullable<bool> IsTriggerOn { get; set; }
        public Nullable<decimal> WithdrawalFrequency { get; set; }
        public Nullable<System.Guid> WithdrawalId { get; set; }
        public Nullable<bool> Allow2FactorAuthentication { get; set; }
        public Nullable<bool> IsOnline { get; set; }
        public Nullable<System.DateTime> SDNCheckDateTime { get; set; }
        public Nullable<bool> AnyPriliminaryHit { get; set; }
        public Nullable<long> ent_num { get; set; }
        public Nullable<bool> IsRequiredImmediatley { get; set; }
        public string DeviceToken { get; set; }
        public string trans_id { get; set; }
        public string user_key { get; set; }
        public string user_pass { get; set; }
        public Nullable<bool> IsSDNSafe { get; set; }
        public string AdminNotes { get; set; }
        public Nullable<System.DateTime> PhoneVerifiedOn { get; set; }
        public string VerificationDocumentPath { get; set; }
    
        public virtual ICollection<MemberNotification> MemberNotifications { get; set; }
        public virtual ICollection<MemberPrivacySetting> MemberPrivacySettings { get; set; }
    }
}
