//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanLordlAPIs.Models.db_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyUnit
    {
        public System.Guid UnitId { get; set; }
        public Nullable<System.Guid> PropertyId { get; set; }
        public string UnitNumber { get; set; }
        public string UnitRent { get; set; }
        public Nullable<System.Guid> BankAccountId { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> LandlordId { get; set; }
        public Nullable<System.Guid> MemberId { get; set; }
        public string UnitImage { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsHidden { get; set; }
        public Nullable<bool> IsOccupied { get; set; }
        public string Status { get; set; }
        public string DueDate { get; set; }
        public string UnitNickName { get; set; }
    }
}
