//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanLordlAPIs.Models.db_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SynapseAddTransactionResult
    {
        public Nullable<System.Guid> TransactionId { get; set; }
        public string OidFromSynapse { get; set; }
        public string Status_DateTimeStamp { get; set; }
        public string Status_Id { get; set; }
        public string Status_Text { get; set; }
        public string Status_Note { get; set; }
        public int Id { get; set; }
    }
}
