//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanLordlAPIs.Models.db_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TenantsIdDocument
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public string DocumentPath { get; set; }
        public Nullable<System.DateTime> UploadedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.Guid> TenantId { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<System.DateTime> VerifiedOn { get; set; }
        public Nullable<System.Guid> VerfiedBy { get; set; }
        public string AdminNotes { get; set; }
    }
}
