//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanLordlAPIs.Models.db_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tenant
    {
        public System.Guid TenantId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string AddressLineOne { get; set; }
        public string AddressLineTwo { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<bool> IsPhoneVerfied { get; set; }
        public string SSN { get; set; }
        public string eMail { get; set; }
        public Nullable<bool> IsEmailVerified { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.Guid> MemberId { get; set; }
        public Nullable<System.Guid> BankAccountId { get; set; }
        public string UserPic { get; set; }
    }
}
